name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          npm run build
          echo "--- Listing build output in runner (dist directory) ---"
          ls -R dist

      - name: Copy frontend files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: 22
          # COPIA O CONTEÚDO da pasta 'dist/public' do runner
          # PARA DENTRO da pasta 'dist' no servidor.
          source: "dist/public/*" 
          target: "${{ secrets.VPS_TARGET_PATH }}/dist"
          overwrite: true 
          # A scp-action DEVE criar o diretório de destino se não existir.

      - name: Set permissions and restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Este é o diretório que o Nginx está configurado para servir
            NGINX_ROOT_DIR="${{ secrets.VPS_TARGET_PATH }}/dist"

            echo "--- Verifying structure in $NGINX_ROOT_DIR after SCP ---"
            if [ ! -d "$NGINX_ROOT_DIR" ]; then
              echo "ERROR: $NGINX_ROOT_DIR does not exist or is not a directory!"
              exit 1
            fi
            ls -la "$NGINX_ROOT_DIR"
            find "$NGINX_ROOT_DIR" -ls

            if [ -f "$NGINX_ROOT_DIR/index.html" ]; then
              echo "SUCCESS: index.html found directly in $NGINX_ROOT_DIR."
            else
              echo "ERROR: index.html NOT found directly in $NGINX_ROOT_DIR. Deployment likely incorrect."
              # exit 1 # Descomente para falhar se a estrutura estiver errada
            fi
            
            echo "Changing permissions for Nginx in $NGINX_ROOT_DIR..."
            sudo chown -R www-data:www-data "$NGINX_ROOT_DIR"
            sudo find "$NGINX_ROOT_DIR" -type d -exec chmod 755 {} \;
            sudo find "$NGINX_ROOT_DIR" -type f -exec chmod 644 {} \;
            
            echo "Restarting Nginx..."
            sudo systemctl restart nginx
            NGINX_STATUS=$(sudo systemctl is-active nginx)
            echo "Nginx status after restart: $NGINX_STATUS"
            if [ "$NGINX_STATUS" != "active" ]; then
              echo "NGINX FAILED TO RESTART! CHECKING LOGS..."
              sudo journalctl -u nginx -n 50 --no-pager
              exit 1
            fi
            echo "Nginx restarted. Deployment complete!"
