name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # Isso gera dist/public/index.html, dist/public/assets/, e dist/index.js (backend)

      # NOVA ETAPA: Preparar o diretório de deployment na VPS
      - name: Prepare deployment directory on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Caminho para o diretório de deploy do frontend
            # Assumindo que VPS_TARGET_PATH é /var/www/ebook.gestolize.com.br
            FRONTEND_DEPLOY_DIR="${{ secrets.VPS_TARGET_PATH }}/dist"
            FRONTEND_DEPLOY_DIR_OLD="${{ secrets.VPS_TARGET_PATH }}/dist_old"

            echo "Preparing deployment directory: $FRONTEND_DEPLOY_DIR"
            
            # Remove a pasta 'dist_old' se existir de um deploy anterior
            if [ -d "$FRONTEND_DEPLOY_DIR_OLD" ]; then
              echo "Removing old backup directory: $FRONTEND_DEPLOY_DIR_OLD"
              sudo rm -rf "$FRONTEND_DEPLOY_DIR_OLD"
            fi
            
            # Se o diretório de deploy atual 'dist' existir, renomeia para 'dist_old' (backup rápido)
            if [ -d "$FRONTEND_DEPLOY_DIR" ]; then
              echo "Backing up current deployment directory $FRONTEND_DEPLOY_DIR to $FRONTEND_DEPLOY_DIR_OLD"
              sudo mv "$FRONTEND_DEPLOY_DIR" "$FRONTEND_DEPLOY_DIR_OLD"
            fi
            
            # Cria o novo diretório 'dist' vazio para o frontend
            echo "Creating new deployment directory: $FRONTEND_DEPLOY_DIR"
            sudo mkdir -p "$FRONTEND_DEPLOY_DIR"
            # Dá propriedade ao usuário SSH para que o scp-action possa escrever
            # Isso é importante! Substitua 'USUARIO_DO_SEGREDO_VPS_SSH_USERNAME' se for diferente de 'root'
            # Se VPS_SSH_USERNAME for 'root', então 'root:root' está correto.
            # Se for outro usuário, use esse usuário.
            sudo chown ${{ secrets.VPS_SSH_USERNAME }}:${{ secrets.VPS_SSH_USERNAME }} "$FRONTEND_DEPLOY_DIR"
            echo "Deployment directory prepared and ownership set for SCP."

      - name: Copy frontend files to VPS via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: 22
          source: "dist/public/" # Copia o CONTEÚDO de dist/public do runner (frontend)
          target: "${{ secrets.VPS_TARGET_PATH }}/dist" # Para /var/www/ebook.gestolize.com.br/dist na VPS
          overwrite: true # Garante que os arquivos sejam sobrescritos

      - name: Finalize deployment and restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Caminho para o diretório de deploy do frontend
            FRONTEND_DEPLOY_DIR="${{ secrets.VPS_TARGET_PATH }}/dist"

            echo "--- Files in $FRONTEND_DEPLOY_DIR after SCP ---"
            ls -lath "$FRONTEND_DEPLOY_DIR"
            
            echo "--- Changing permissions for Nginx ---"
            sudo chown -R www-data:www-data "$FRONTEND_DEPLOY_DIR"
            sudo find "$FRONTEND_DEPLOY_DIR" -type d -exec chmod 755 {} \;
            sudo find "$FRONTEND_DEPLOY_DIR" -type f -exec chmod 644 {} \;
            
            echo "--- Restarting Nginx ---"
            sudo systemctl restart nginx
            echo "Nginx restarted. Frontend deployment complete!"
